# Site settings
title: bridgekeeper
description:
  Must answer me
  These questions three
  Ere the other side he see
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://example.gov" # the base hostname & protocol for your site

colors:
  background: '#ffffff'
  button:
    background: '#0071bc'
    hover: '#3e94cf'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  projects:
    accent: '#02bfe7'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    background: '#323a45'
    text: '#fff'

analytics:
  google:
    code: 'UA-48605964-32' # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency


# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

collections:
  people:
    output: false
